[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = "0.7.0"
actix-web = "4"
serde ={version = "1.0.210", features= ["derive"]}
serde_json = "1.0.128"
common = { path = "../common" }
